
package com.soap.service;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerInfo", targetNamespace = "http://service.soap.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerInfo {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServerName", targetNamespace = "http://service.soap.com/", className = "com.soap.service.GetServerName")
    @ResponseWrapper(localName = "getServerNameResponse", targetNamespace = "http://service.soap.com/", className = "com.soap.service.GetServerNameResponse")
    @Action(input = "http://service.soap.com/ServerInfo/getServerNameRequest", output = "http://service.soap.com/ServerInfo/getServerNameResponse")
    public String getServerName();

}
