
package com.ws.demo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://demo.ws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHelloWorld", targetNamespace = "http://demo.ws.com/", className = "com.ws.demo.GetHelloWorld")
    @ResponseWrapper(localName = "getHelloWorldResponse", targetNamespace = "http://demo.ws.com/", className = "com.ws.demo.GetHelloWorldResponse")
    public String getHelloWorld(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
